### ISSUE TITLE
Can't find game

### ISSUE THREAD

**Issue by SpicyClown69** [Kariaro/SMInjector#2]
If I try and run it it gives an error and it thinks that the game is in [C:\Program Files (x86)\Steam\steamapps\common\Scrap Mechanic] but I have a custom install location and the game is on my D:\ drive

**Comment by Kariaro** [comment]
This injector is not updated for the new versions of the game and will not work.

There is currently a new mod project that I'm not affiliated with that you can find here (All code is not available yet).
https://github.com/Scrap-Mechanic-Modding

There is also another fork of this repo that has more content but I'm not sure if it will work.
https://github.com/TechnologicNick/SMInjector

**Comment by SpicyClown69** [comment]
nvm it works lol

**Comment by SpicyClown69** [comment]
I had some old files in there from a previous install that was throwing it off
